home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: reservations
        permanent: true
reservations:
    path: /reservations
    controller: App\Controller\ReservationController::index
reservations_export:
    path: /reservations/{format}
    controller: App\Controller\ReservationController::export
